#!/bin/sh
# Hook credit to tpope (http://tpo.pe)
set -e
PATH="/usr/local/bin:$PATH"
dir=$(git rev-parse --git-dir)
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
git ls-files | ctags --tag-relative -L - -f$dir/tags.$$ --fields=+ia --languages=-javascript,sql
mv $dir/tags.$$ $dir/tags
