#!/bin/zsh

# Print colored load averages for tmux status line
function () {
  local ncores=$(awk '/siblings/ {print $3; exit}' /proc/cpuinfo)
  local -a loadavg=( $(cut -d ' ' -f 1-3 /proc/loadavg) )

  for (( i=1; i <= $#loadavg; ++i )); do
    if (( loadavg[i] >= ncores * 0.75 )); then
      loadavg[$i]="#[fg=red]$loadavg[$i]"
    elif (( loadavg[i] >= ncores * 0.5 )); then
      loadavg[$i]="#[fg=yellow]$loadavg[$i]"
    else
      loadavg[$i]="#[fg=green]$loadavg[$i]"
    fi
  done

  print "${loadavg}#[fg=default]"
}

