# vim: ft=yaml.ansible

- name: Clean deps before rebuild
  when: clone_result | default(false)
  block:
    - name: Check if .deps already built
      ansible.builtin.stat:
        path: "{{ (clone_path, '.deps') | path_join }}"
      register: deps_dir

    - name: Run `make distclean`
      community.general.make:
        chdir: "{{ clone_path }}"
        target: distclean
      when: deps_dir.stat.exists
