# vim: ft=yaml.ansible

- name: Ensure repository state
  block:
    - name: "Clone Neovim and checkout {{ build.tag }}"
      ansible.builtin.git: &clone_opts
        dest: "{{ build.path }}"
        repo: https://github.com/neovim/neovim
        version: "{{ build.tag }}"
      register: clone_result
  rescue:
    - name: Work around tag reuse
      when: clobber
      vars:
        clobber: "{{ 'would clobber existing tag' in ansible_failed_result.msg }}"
      block:
        - name: Force tag fetch
          ansible.builtin.command: # noqa: command-instead-of-module
            cmd: git fetch --force
            chdir: "{{ build.path }}"
          register: force_fetch
          changed_when: "'forced' in force_fetch.stdout"
          check_mode: false

        - name: Checkout updated tag
          ansible.builtin.git:
            <<: *clone_opts

    - name: Fail on any other checkout error
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result.msg }}"
      when: not clobber
