# vim: ft=yaml.ansible

- name: Build Neovim nightly ({{ build_type }})
  community.general.make:
    chdir: "{{ clone_path }}"
    params:
      CMAKE_BUILD_TYPE: "{{ build_type }}"

- name: Install Neovim nightly
  become: true
  community.general.make:
    chdir: "{{ clone_path }}"
    target: install
