# vim: ft=yaml.ansible

- name: Build Neovim nightly ({{ build.type }})
  community.general.make:
    chdir: "{{ build.path }}"
    params:
      CMAKE_BUILD_TYPE: "{{ build.type }}"

- name: Install Neovim nightly
  become: true
  community.general.make:
    chdir: "{{ build.path }}"
    target: install
