# vim: ft=yaml.ansible

- name: Get latest upstream kitty release
  ansible.builtin.uri:
    url: https://api.github.com/repos/kovidgoyal/kitty/releases/latest
    method: GET
  register: kitty_release

- name: Install latest upstream kitty release
  become: true
  vars:
    version: "{{ kitty_release.json.tag_name | trim('v') }}"
    filename: "kitty-{{ version }}-{{ ansible_architecture }}.txz"
    asset: "{{ kitty_release.json.assets | selectattr('name', 'eq', filename) | first }}"
  ansible.builtin.unarchive:
    src: "{{ asset.browser_download_url }}"
    remote_src: true
    dest: /usr/local
