# vim: ft=yaml.ansible

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Configure package manager (Suse)
  become: true
  when: ansible_os_family == 'Suse'
  vars:
    config: /etc/zypp/zypp.conf
  block:
    - name: Don't include recommended packages by default
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "solver\\.onlyRequires\\s*=\\s*(false|true)"
        line: "solver.onlyRequires = true"

    - name: Don't allow vendor change on dist-upgrade by default
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "solver\\.dupAllowVendorChange\\s*=\\s*(true|false)"
        line: "solver.dupAllowVendorChange = false"

    - name: Don't allow architecture change on dist-upgrade by default
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "solver\\.dupAllowArchChange\\s*=\\s*(true|false)"
        line: "solver.dupAllowArchChange = false"

    - name: "[mirrorsorcerer] Increase repo auto-refresh delay to 18 hours"
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "repo\\.refresh.delay\\s*=\\s*\\d*"
        line: "repo.refresh.delay = 1080"

    # Disable chunking package downloads across multiple mirrors when metalink
    # data is present. Prior to the libzypp-17.36.4 / zypper-1.14.87 update, the
    # MULTICURL backend used this for connection chunking.
    - name: "[mirrorsorcerer] Do not chunk connections to avoid tanking performance"
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "download\\.max_concurrent_connections\\s*=\\s*\\d*"
        line: "download.max_concurrent_connections = 1"
      when: >-
        ansible_facts.packages['libzypp'] | selectattr('version', 'version', '17.36.4', '<') is any and
        ansible_facts.packages['zypper'] | selectattr('version', 'version', '1.14.87', '<') is any

    # As of libzypp-17.36.4 / zypper-1.14.87, actual parallel downloads will
    # will be used. Increase the max download count a bit.
    - name: "[zypp-parallel] Increase max concurrent downloads to 8"
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "download\\.max_concurrent_connections\\s*=\\s*\\d*"
        line: "download.max_concurrent_connections = 8"
      when: >-
        ansible_facts.packages['libzypp'] | selectattr('version', 'version', '17.36.4', '>=') is any and
        ansible_facts.packages['zypper'] | selectattr('version', 'version', '1.14.87', '>=') is any

    # By default, this is unset and just means zypper picks a "sane default".
    # Let's be explicit.
    - name: "[mirrorsorcerer] Ensure packages are downloaded in advance"
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "commit\\.downloadMode\\s*="
        line: "commit.downloadMode = DownloadInAdvance"

    # Don't waste time on slow connections
    - name: Set minimum download speed to 25KB/s
      ansible.builtin.lineinfile:
        path: "{{ config }}"
        regexp: "download\\.min_download_speed\\s*=\\s*\\d*"
        line: "download.min_download_speed = {{ 1024 * 25 }}"
