cmdargs:
  color: true
  env:
    neovim: true
  severity: 'style_problem'
  stat: true

policies:
  ProhibitMissingScriptEncoding:
    enabled: false
  ProhibitImplicitScopeVariable:
    enabled: false
