# vim: ft=yaml.ansible

- name: Build customized Iosevka Font Family
  hosts: localhost
  vars_files:
    - vars/main.yml
  vars:
    build_plans: "{{ (iosevka_dir, 'iosevka-zero-build-plans.toml') | path_join }}"
    iosevka_dir: "{{ (dotfiles, 'fonts', 'Iosevka') | path_join }}"
    iosevka_docker: /tmp/Iosevka/docker
    patched_fonts: "{{ (iosevka_dir, 'patched') | path_join }}"
  tasks:
    - name: Check dists directory
      ansible.builtin.stat:
        path: "{{ (iosevka_dir, 'dist') | path_join }}"
      register: st_dist

    - name: Check build plans
      ansible.builtin.stat:
        path: "{{ build_plans }}"
      register: st_plans
      failed_when: not st_plans.stat.exists

    - name: Build font
      when: not st_dist.stat.exists or st_plans.stat.mtime > st_dist.stat.mtime
      block:
        # NOTE: We only need the docker subtree; the resulting container will
        # always pull the latest Iosevka release for building
        - name: Sparse clone be5invis/Iosevka
          # noqa: command-instead-of-module
          ansible.builtin.command: |
            git clone --sparse --filter=blob:none 'https://github.com/be5invis/Iosevka'
            git sparse-checkout set docker/
          args:
            chdir: /tmp
            creates: "{{ (iosevka_docker, 'Dockerfile') | path_join }}"

        - name: Build fontcc container
          community.docker.docker_image_build:
            name: fontcc
            path: "{{ iosevka_docker }}"

        - name: Link build plan
          ansible.builtin.file:
            src: "{{ build_plans }}"
            dest: "{{ (iosevka_dir, 'private-build-plans.toml') | path_join }}"
            state: link

        - name: Compile Iosevka Zero
          community.docker.docker_container:
            name: ansible-build-iosevka-zero
            image: fontcc
            command: ttf::iosevka-zero
            working_dir: "{{ iosevka_dir }}"
            volumes:
              - "{{ iosevka_dir }}:/work"
            cleanup: true
            detach: false # Wait for container to exit
            pull: never
          tags: build

    - name: Pull nerdfonts/patcher
      community.docker.docker_image_pull:
        name: nerdfonts/patcher

    - name: Patch Iosevka Zero
      community.docker.docker_container:
        name: ansible-patch-iosevka-zero
        image: nerdfonts/patcher
        command: -c --makegroups -1
        working_dir: "{{ iosevka_dir }}"
        volumes:
          - "{{ (iosevka_dir, 'dist/iosevka-zero/TTF') | path_join }}:/in"
          - "{{ patched_fonts }}:/out"
        env:
          PN: "16" # job count
        cleanup: true
        detach: false # Wait for container to exit
      tags: build

    - name: Deploy font
      block:
        - name: Gather font files
          ansible.builtin.find:
            paths: "{{ patched_fonts }}"
          register: fonts

        - name: Deploy Iosevka Zero font
          ansible.builtin.file:
            src: "{{ item.path }}"
            dest: "{{ (data_dir, 'fonts', (item.path | basename)) | path_join }}"
            state: link
            force: true
          loop: "{{ fonts.files }}"
          loop_control:
            label: "{{ item.path }}"
