[selene]
base = 'lua51'
name = 'zeroknight'

[vim]
any = true

[jit]
any = true

[bit]
any = true

[zeroknight]
property = true
writable = 'new-fields'

[packer_plugins]
property = true
writable = 'new-fields'

[[dump.args]]
type = '...'
required = true

[[as_stdpath.args]]
type = ['cache', 'config', 'config_dirs', 'data', 'data_dirs']
required = true

[[as_stdpath.args]]
type = 'string'
required = true

[[has.args]]
type = 'string'
required = true

[[reload.args]]
type = 'string'
required = true

[[rerequire.args]]
type = 'string'
required = true

[[packer_loaded.args]]
type = 'string'
required = true
